### ISSUE TITLE
Build fail of qtkeychaine 0.3.0 on MacOS

### ISSUE THREAD

**Issue by hibagnet** [owncloud/homebrew-owncloud#3]
$ brew install qtkeychain
==> Installing qtkeychain from owncloud/homebrew-owncloud
==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/qtkeychain-0.3.tar.gz
==> Patching
==> cmake . -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qtkeychain/0.3 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIN
==> make install
make[2]: *** [CMakeFiles/qt5keychain.dir/moc_keychain_p.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/qt5keychain.dir/keychain_mac.cpp.o] Error 1
make[1]: *** [CMakeFiles/qt5keychain.dir/all] Error 2
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/owncloud/homebrew-owncloud/issues

**Comment by te-online** [comment]
@hibagnet Did you solve this problem? Still running into the same problem.

**Comment by kramer65** [comment]
I'm also running in a problem while compiling. Any tips would be greatly appreciated.

**Comment by danimo** [comment]
Bumped it to v0.6.2. Try again please.

**Comment by kramer65** [comment]
I just tried, but I now get the following error:

```
$ brew install qtkeychain
==> Installing qtkeychain from owncloud/owncloud
==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/0.6.2.tar.gz
==> Downloading from https://codeload.github.com/frankosterfeld/qtkeychain/tar.gz/0.6.2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "qtkeychain"
Download failed: https://codeload.github.com/frankosterfeld/qtkeychain/tar.gz/0.6.2
```

**Comment by kramer65** [comment]
Hi @danimo 
I don't know if you changed anything, but I just tried again and I now get a different error:
```
$ brew install qtkeychain
==> Installing qtkeychain from owncloud/owncloud
==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/v0.6.2.tar.gz
==> Downloading from https://codeload.github.com/frankosterfeld/qtkeychain/tar.gz/v0.6.2
######################################################################## 100,0%
Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.
Error: SHA1 mismatch
Expected: da39a3ee5e6b4b0d3255bfef95601890afd80709
Actual: 9aa8e205a80130368be131bd1eb78d03799e405d
Archive: /Library/Caches/Homebrew/qtkeychain-0.6.2.tar.gz
To retry an incomplete download, remove the file above.
```

I'm really dependent on qtkeychain to compile some software. You would really make my day, or actually my week if I could get this going.

Would you have any other idea how this could be solved? All tips are welcome!

**Comment by danimo** [comment]
Ok, finally got the chance to work on this on a real mac. The fomula now builds for me without warnings.

**Comment by kramer65** [comment]
Awesome! It now works like a charm!

Thanks!
